version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.0
    working_directory: /go/src/github.com/karamaru-alpha/layered-arch-sample
    steps:
      - checkout
      - run:
          name: Install golangci-lint@v1.30.0
          command: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.30.0
      - run:
          name: Run golangci-lint
          command: golangci-lint run
